version: '3.8'

services:
  eureka-server:
    build: ./eureka server/demo
    container_name: eureka-server
    ports:
      - "8761:8761"

  todo-app:
    build: ./bd/demo
    container_name: todo-app
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server


  todo-app-2:
    build: ./bd/demo
    container_name: todo-app-2
    ports:
      - "5050:8080"
    depends_on:
      - eureka-server
